name: Industrie IT
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7199
title: Industrie IT
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#212121'
    - '#78bb20'
    - '#609f20'
    - '#000000'
    - '#808000'
  brandStrength: 0
  lightness: 0.7695115632377565
  saturation: 0.5
  rhythmicContrast: 0.7179543878883123
purpose: []
